### ISSUE TITLE
No data transfer

### ISSUE THREAD

**Issue by htom89** [bembelstemmer/ioBroker.batrium-bms#12]
Hello,
first of all thanks for developing the adapter.
The installation worked.
Unfortunately, no data transfer takes place. Do I have to adjust something in the Batrium?

![image](https://user-images.githubusercontent.com/70407213/225286176-1313c372-c702-4961-b644-8d67da3b4461.png)

![image](https://user-images.githubusercontent.com/70407213/225286291-671d1c6c-9dd1-4e8b-a593-1173628132ce.png)

![image](https://user-images.githubusercontent.com/70407213/225286564-573c4a60-0855-45a7-9c0d-c2dce467de47.png)

![image](https://user-images.githubusercontent.com/70407213/225286668-b64c0cbe-c296-4338-89c2-989f27da3c28.png)

![image](https://user-images.githubusercontent.com/70407213/225286821-4b5f3242-a5cc-4e01-996b-8ddc37f33f57.png)

![image](https://user-images.githubusercontent.com/70407213/225286983-2ea206ff-6636-4994-8ac4-f9420280c51e.png)

![image](https://user-images.githubusercontent.com/70407213/225287218-3450fbe4-45f2-49a4-ae9a-ec578daa857c.png)

I hope you can help me :)
Thank you.

**Comment by bembelstemmer** [comment]
Hi, the configuration is looking fine. Basically identical to my setup.
Just to make sure. Do you run the ioBroker Instance and WatchmonToolkit on the same PC?
Because that's not possible as only one application is able to grab the port. But then you should have some error message in the logs.

Could you try to switch the Loglevel for the Adapter to debug temporarily please? Then you should get Log lines for every UDP message the Adapter receives. I have no real other idea at the moment as the Port cannot be changed on the Watchmon as far as i know.
With Verbose Broadcast it should immediately look like this:
![grafik](https://user-images.githubusercontent.com/1917502/225421976-2eb8362c-8067-45d5-8649-6d68766b0c6d.png)

**Comment by htom89** [comment]
Good morning,
i found the mistake. :)
Sorry it was my mistake.
In Docker, the port was activated on TCP and not on UDP.
![image](https://user-images.githubusercontent.com/70407213/225543914-464d7f19-b0f6-4cdf-bcdc-951498f2b747.png)

Thanks again for your help!
Have a nice day!

**Comment by bembelstemmer** [comment]
Ah, good finding. Very good. Maybe i‘ll add that note to the documentation for others.
I‘m happy someone else is using the adapter too and it‘s not useless.
Hopefully i‘ll have more time soon to extend the supported Message types.

Cheers
